version: '3'

services:

  nginx:
    container_name: ${SERVICE_NAME}_nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html
    ports:
      - "${NGINX_PORT}:80"
    links:
      - php

  php:
    container_name: ${SERVICE_NAME}_php
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: always
    expose:
      - ${PHP_EXPOSE}
    ports:
      - "${PHP_PORT}:9000"
    links:
      - mysql
      - redis
    volumes:
      - ../app:/var/www/html

  mysql:
    container_name: ${SERVICE_NAME}_mysql
    image: mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
        MYSQL_USER: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SERVICE_TAGS: ${SERVICE_TAGS}
        SERVICE_NAME: ${SERVICE_NAME}
    tty: true

  redis:
    container_name: ${SERVICE_NAME}_redis
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/var/lib/data
    command: redis-server --appendonly yes